export const sessionData = {
  session1: {
    date: "2024-04-20",
    time: "10:00 AM",
    session_id: "session1",
    test_sequence: "sequence1",
  },
  session2: {
    date: "2024-04-21",
    time: "11:00 AM",
    session_id: "session2",
    test_sequence: "sequence2",
  },
  session3: {
    date: "2024-04-22",
    time: "12:00 PM",
    session_id: "session3",
    test_sequence: "sequence3",
  },
  session4: {
    date: "2024-04-23",
    time: "1:00 PM",
    session_id: "session4",
    test_sequence: "sequence1",
  },
  session5: {
    date: "2024-04-23",
    time: "2:00 PM",
    session_id: "session5",
    test_sequence: "sequence2",
  },
  session6: {
    date: "2024-04-24",
    time: "3:00 PM",
    session_id: "session6",
    test_sequence: "sequence3",
  },
  session7: {
    date: "2024-04-25",
    time: "4:00 PM",
    session_id: "session7",
    test_sequence: "sequence1",
  },
  session8: {
    date: "2024-04-25",
    time: "5:00 PM",
    session_id: "session8",
    test_sequence: "sequence2",
  },
  session9: {
    date: "2024-04-26",
    time: "6:00 PM",
    session_id: "session9",
    test_sequence: "sequence3",
  },
  session10: {
    date: "2024-04-27",
    time: "7:00 PM",
    session_id: "session10",
    test_sequence: "sequence1",
  },
};

export const sessionDetails = {
  session1: {
    session_id: "session1",
    data: [
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
    ],
  },
  session2: {
    session_id: "session2",
    data: [
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
    ],
  },
  session3: {
    session_id: "session3",
    data: [
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
    ],
  },
  session4: {
    session_id: "session4",
    data: [
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
    ],
  },
  session5: {
    session_id: "session5",
    data: [
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
    ],
  },
  session6: {
    session_id: "session6",
    data: [
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
    ],
  },
  session7: {
    session_id: "session7",
    data: [
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
    ],
  },
  session8: {
    session_id: "session8",
    data: [
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
    ],
  },
  session9: {
    session_id: "session9",
    data: [
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
    ],
  },
  session10: {
    session_id: "session10",
    data: [
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
      {
        "x-coordinates": 0,
        "real_x-coordinates": 0,
        "y-coordinates": 1.36144,
        "real_y-coordinates": 1.36144,
        "z-coordinates": 0,
        "real_z-coordinates": 0,
        rotation: 0,
        real_rotation: 0,
      },
    ],
  },
};
